[package]
name = "createrepo-rs"
version = "0.1.0"
authors = ["René Richter <richterrettich@gmail.com>"]
edition = "2018"

[lib]
name="rpm"
path="src/rpm/rpm.rs"

[dependencies]
quick-xml = "0.14.0"
nom = "5.0.0-beta2"
num-traits = "0.2"
num-derive = "0.2"
num = "0.2.0"
enum-display-derive = "0.1.0"
cpio = "0.2.0"
rust-lzma = "0.4"
libflate = "0.1.23"
sha2 = "0.8.0"
md-5 = "0.8.0"
sha1 = "0.6.0"